name: "Bump Version"

on:
  push:
    branches:
      - "main"

jobs:
  bump-version:
    name: ðŸš€ Bump Version on master
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout source code
        uses: "actions/checkout@v3"
        with:
          ref: ${{ github.ref }}
      - name: ðŸ“„ cat package.json
        run: cat ./package.json

      - name: âŽ” Setup Node.js
        uses: "actions/setup-node@v3"
        with:
          node-version: 18
      - name: âœ¨ Automated Version Bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ðŸ“„ cat package.json
        run: cat ./package.json
